# Generated by Django 4.1.3 on 2023-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antiques',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('valuation', models.FloatField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
