# Generated by Django 4.1.7 on 2023-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0002_antiques_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiques',
            name='fun_facts',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='antiques',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
