# Generated by Django 4.1.7 on 2023-04-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0003_antiques_fun_facts_alter_antiques_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antiques',
            old_name='index',
            new_name='id',
        ),
    ]
