# Generated by Django 4.1.7 on 2023-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0004_rename_index_antiques_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiques',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
