# Generated by Django 4.1.7 on 2023-04-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0005_antiques_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='index',
            new_name='id',
        ),
    ]
