# Generated by Django 4.1.7 on 2023-04-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0006_rename_index_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('antique_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiques.antiques')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiques.user')),
            ],
        ),
    ]
