# Generated by Django 4.1.7 on 2023-04-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0007_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiques',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
