# Generated by Django 4.1.7 on 2023-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0008_antiques_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiques',
            name='creator',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
