# Generated by Django 4.1.7 on 2023-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0010_alter_antiques_creator_alter_antiques_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiques',
            name='name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
