# Generated by Django 4.1.7 on 2023-04-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0013_rename_password_user_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
