# Generated by Django 4.2.1 on 2023-05-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0018_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiques',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
