# Generated by Django 4.2.1 on 2023-06-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0020_antiques_subtype_alter_antiques_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiques',
            name='subtype',
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('antique_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiques.antiques')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiques.user')),
            ],
        ),
    ]
