# Generated by Django 4.2.1 on 2023-06-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0021_remove_antiques_subtype_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='antique_id',
        ),
        migrations.CreateModel(
            name='AntiquesCollections',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('antique_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiques.antiques')),
                ('collection_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiques.collections')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antiques.user')),
            ],
        ),
    ]
